version: '3.5'

volumes:
  data:
    driver: local

services:
  mysql:
    image: mysql:5.7
    container_name: egresso-mysql
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=evasao
      - MYSQL_USER=bruno
      - MYSQL_PASSWORD=
    networks:
    - dev

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: egresso-app
    volumes:
      - .:/var/www/app
    ports:
      - "8181:8181"
      - "8083:8083"
    depends_on:
      - mysql
    networks:
    - dev

networks:
  dev:
    name: tr_network