version: '3.5'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: egresso-app
    volumes:
      - ./var/www/html/egresso2.0:/var/www/egresso2.0
    ports:
      - "8181:8181"
      - "8083:8083"
    command: /run.sh
    depends_on:
      - mysql
    networks:
      - dev

  mysql:
    image: mysql:5.7
    container_name: egresso-mysql
    volumes:
      - ./:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=evasao
      - MYSQL_USERNAME=bruno
      - MYSQL_PASSWORD=secret
    networks:
      - dev

volumes:
  data:
    driver: local

networks:
  dev:
    name: egresso