version: '3.5'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: egresso-app
    volumes:
      - ./:/app
    ports:
      - "8181:8181"
      - "8083:8083"
    command: /run.sh
    depends_on:
      - mysql
    networks:
      - dev

  mysql:
    container_name: egresso-mysql
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USERNAME=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    build:
      context: .
      dockerfile: ./database/db/dockerfile.db
    networks:
      - dev

# volumes:
#   db-data: ./database

networks:
  dev:
    name: egresso